name: flet_svg
description: Flet FletSvg control
repository: https://github.com/MyGithubAccount/flet-svg/src/flutter/flet_svg
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-svg

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.28.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
